version: '3.8'

services:
  email_checker:
    build: .
    restart: always
    environment:
      - CONFIG_FILE=/app/config.py
      - LANGUAGE=Chinese  # Chinese or English
      - TIMEZONE=Asia/Shanghai # 设置你的时区(set your preferred timezone)
    volumes:
      - ./config.py:/app/config.py
