services:
  mail2telegram:
    build: .
    container_name: mail2telegram
    restart: always
    environment:
      - CONFIG_FILE=/app/config.py
      - LANGUAGE=Chinese  # Chinese or English
      - TIMEZONE=Asia/Shanghai # 设置你的时区
      - ENABLE_LOGGING=true  # 是否开启日志
      - ENABLE_EVC=true # 扩展功能，提取邮件验证码后发送到剪贴板，搭配 Jeric-X/SyncClipboard 使用, 在项目的tools/send_code.py配置
    volumes:
      - ./config.py:/app/config.py
      - ./log:/app/log
      - ./tools:/app/tools
    logging:
      driver: "json-file"
      options:
        max-size: "5m"  # 设置日志文件的最大大小为5MB
        max-file: "5"   # 保留最多5个日志文件
    networks:
      - ai  # 使用共享网络

networks:
  ai:
    external: true  # 使用外部创建的共享网络
