services:
  mail2telegram:
    build: .
    container_name: mail2telegram
    restart: always
    environment:
      - CONFIG_FILE=/app/config.py
      - LANGUAGE=Chinese  # Chinese or English
      - TIMEZONE=Asia/Shanghai # 设置你的时区
      - ENABLE_LOGGING=true  # 是否开启日志
      - ENABLE_EVC=false # 扩展功能，提取邮件验证码后发送到剪贴板
    volumes:
      - ./config.py:/app/config.py
      - ./log:/app/log
      - ./tools:/app/tools
    logging:
      driver: "json-file"
      options:
        max-size: "5m" 
        max-file: "5" 
# 扩展内容，若不需要请把下面全部删除
    networks:
      - evc 

networks:
  evc:
    name: evc
    driver: bridge
    external: false

